/**
 * DeFi Analysis — Content Loader
 * Loads content synced from Webflow CMS via webflow_sync.py.
 *
 * Content file (js/content.json) is generated by:
 *   python3 webflow_sync.py
 *
 * When content.json is present and non-empty, CMS content populates
 * the page. Otherwise, the static HTML content is used as fallback.
 */

(function () {
  'use strict';

  var CONTENT_URL = 'js/content.json';

  /**
   * Populate a section from CMS content.
   * Looks for items whose slug or category matches the section id.
   */
  function populateSection(section, contentItems) {
    var sectionId = section.getAttribute('data-cms-section');
    if (!sectionId) return;

    // Find matching items
    var matches = contentItems.filter(function (item) {
      return item.slug === sectionId || item.category === sectionId;
    });

    if (!matches.length) return;

    // Update section title and body from first matching item
    var mainItem = matches[0];
    var titleEl = section.querySelector('.section__title');
    var bodyEl = section.querySelector('.section__body');

    if (titleEl && mainItem.name) {
      titleEl.textContent = mainItem.name;
    }
    if (bodyEl && mainItem.description) {
      bodyEl.textContent = mainItem.description;
    }

    // If there's rich HTML content, inject it
    if (mainItem.content && bodyEl) {
      bodyEl.innerHTML = mainItem.content;
    }
  }

  /**
   * Populate ecosystem items from CMS content.
   */
  function populateEcosystem(container, contentItems) {
    var ecosystemItems = contentItems.filter(function (item) {
      return item.category === 'ecosystem' || item.slug === 'ecosystem';
    });

    if (!ecosystemItems.length) return;

    // Sort by order
    ecosystemItems.sort(function (a, b) { return (a.order || 0) - (b.order || 0); });

    var existingItems = container.querySelectorAll('.eco-item');
    ecosystemItems.forEach(function (item, i) {
      if (i < existingItems.length) {
        var el = existingItems[i];
        var title = el.querySelector('.eco-item__title');
        var desc = el.querySelector('.eco-item__desc');
        var examples = el.querySelector('.eco-item__examples');

        if (title && item.name) title.textContent = item.name;
        if (desc && item.description) desc.textContent = item.description;
        if (examples && item.content) examples.textContent = item.content;
      }
    });
  }

  /**
   * Populate pathway steps from CMS content.
   */
  function populatePathway(container, contentItems) {
    var steps = contentItems.filter(function (item) {
      return item.category === 'pathway' || item.slug === 'pathway' || item.slug === 'engagement';
    });

    if (!steps.length) return;

    steps.sort(function (a, b) { return (a.order || 0) - (b.order || 0); });

    var existingSteps = container.querySelectorAll('.pathway__step');
    steps.forEach(function (item, i) {
      if (i < existingSteps.length) {
        var el = existingSteps[i];
        var title = el.querySelector('.pathway__title');
        var desc = el.querySelector('.pathway__body p');

        if (title && item.name) title.textContent = item.name;
        if (desc && item.description) desc.textContent = item.description;
      }
    });
  }

  /**
   * Update key figures from CMS data.
   */
  function populateFigures(container, contentItems) {
    var figureItems = contentItems.filter(function (item) {
      return item.category === 'figures' || item.slug === 'figures';
    });

    if (!figureItems.length) return;

    var existingFigures = container.querySelectorAll('.figure');
    figureItems.forEach(function (item, i) {
      if (i < existingFigures.length) {
        var valueEl = existingFigures[i].querySelector('.figure__value');
        var labelEl = existingFigures[i].querySelector('.figure__label');
        var noteEl = existingFigures[i].querySelector('.figure__note');

        if (valueEl && item.name) valueEl.textContent = item.name;
        if (labelEl && item.description) labelEl.textContent = item.description;
        if (noteEl && item.content) noteEl.textContent = item.content;
      }
    });
  }

  /**
   * Load and apply CMS content.
   */
  function loadContent() {
    fetch(CONTENT_URL)
      .then(function (res) {
        if (!res.ok) throw new Error('Content file not available');
        return res.json();
      })
      .then(function (data) {
        if (!data.content || !data.content.length) {
          console.log('[ContentLoader] No CMS content found — using static content.');
          return;
        }

        console.log('[ContentLoader] Loaded CMS content from ' +
          data.sites.length + ' site(s), ' + data.content.length + ' collection(s).');

        // Flatten all items across collections
        var allItems = [];
        data.content.forEach(function (col) {
          allItems = allItems.concat(col.items);
        });

        console.log('[ContentLoader] Applying ' + allItems.length + ' items to page.');

        // Populate each section
        document.querySelectorAll('[data-cms-section]').forEach(function (section) {
          populateSection(section, allItems);
        });

        // Populate ecosystem
        var ecoGrid = document.getElementById('ecosystem-grid');
        if (ecoGrid) populateEcosystem(ecoGrid, allItems);

        // Populate pathway
        var pathway = document.getElementById('pathway-steps');
        if (pathway) populatePathway(pathway, allItems);

        // Populate figures
        var figures = document.getElementById('figures-grid');
        if (figures) populateFigures(figures, allItems);

        console.log('[ContentLoader] Page content updated from Webflow CMS.');
      })
      .catch(function (err) {
        console.log('[ContentLoader] Using static content (' + err.message + ').');
        console.log('[ContentLoader] Run "python3 webflow_sync.py" to sync from Webflow CMS.');
      });
  }

  // Load on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', loadContent);
  } else {
    loadContent();
  }

})();
